In [1]:
from tensorflow.keras.preprocessing.text import one_hot 

In [3]:
### sentences
sent=[  'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## define the vocabulary size 

voc_size = 10000 

In [5]:
## One Hot rep of every word 

one_hot_rep = [one_hot(words, voc_size) for words in sent]


In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
one_hot_rep

[[5881, 2317, 1351, 7350],
 [5881, 2317, 1351, 694],
 [5881, 352, 1351, 1984],
 [6281, 5629, 8244, 4994, 4179],
 [6281, 5629, 8244, 4994, 1363],
 [3622, 5881, 4571, 1351, 2031],
 [8908, 3409, 1457, 4994]]

In [9]:
## word embedding representation 

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np 

In [11]:
sent_length = 8 

embedded_docs = pad_sequences(one_hot_rep, padding= 'pre', maxlen= sent_length)
print(embedded_docs)

[[   0    0    0    0 5881 2317 1351 7350]
 [   0    0    0    0 5881 2317 1351  694]
 [   0    0    0    0 5881  352 1351 1984]
 [   0    0    0 6281 5629 8244 4994 4179]
 [   0    0    0 6281 5629 8244 4994 1363]
 [   0    0    0 3622 5881 4571 1351 2031]
 [   0    0    0    0 8908 3409 1457 4994]]


In [12]:
## feature represntation 

dim = 10 

In [13]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam', 'mse')

2025-04-17 10:17:38.630487: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2025-04-17 10:17:38.630712: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-04-17 10:17:38.630732: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2025-04-17 10:17:38.631121: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-04-17 10:17:38.631439: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [14]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

2025-04-17 10:18:22.281942: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 296ms/step


array([[[ 0.0346227 , -0.02082778, -0.00693996,  0.03412033,
         -0.03133487,  0.00181317,  0.04882843,  0.04206527,
         -0.0313372 , -0.0029693 ],
        [ 0.0346227 , -0.02082778, -0.00693996,  0.03412033,
         -0.03133487,  0.00181317,  0.04882843,  0.04206527,
         -0.0313372 , -0.0029693 ],
        [ 0.0346227 , -0.02082778, -0.00693996,  0.03412033,
         -0.03133487,  0.00181317,  0.04882843,  0.04206527,
         -0.0313372 , -0.0029693 ],
        [ 0.0346227 , -0.02082778, -0.00693996,  0.03412033,
         -0.03133487,  0.00181317,  0.04882843,  0.04206527,
         -0.0313372 , -0.0029693 ],
        [-0.02591617, -0.00051349,  0.03782333, -0.02742329,
          0.00983693, -0.00701687, -0.04394136, -0.00390934,
          0.01345844, -0.01327621],
        [-0.04100574,  0.02606461, -0.04599339,  0.02386352,
          0.02503207, -0.03597945, -0.0194989 ,  0.02387352,
          0.00207195, -0.02740302],
        [-0.01656395, -0.02776014, -0.00654156, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 5881, 2317, 1351, 7350], dtype=int32)

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 137ms/step


array([[ 0.0346227 , -0.02082778, -0.00693996,  0.03412033, -0.03133487,
         0.00181317,  0.04882843,  0.04206527, -0.0313372 , -0.0029693 ],
       [ 0.0346227 , -0.02082778, -0.00693996,  0.03412033, -0.03133487,
         0.00181317,  0.04882843,  0.04206527, -0.0313372 , -0.0029693 ],
       [ 0.0346227 , -0.02082778, -0.00693996,  0.03412033, -0.03133487,
         0.00181317,  0.04882843,  0.04206527, -0.0313372 , -0.0029693 ],
       [ 0.0346227 , -0.02082778, -0.00693996,  0.03412033, -0.03133487,
         0.00181317,  0.04882843,  0.04206527, -0.0313372 , -0.0029693 ],
       [-0.02591617, -0.00051349,  0.03782333, -0.02742329,  0.00983693,
        -0.00701687, -0.04394136, -0.00390934,  0.01345844, -0.01327621],
       [-0.04100574,  0.02606461, -0.04599339,  0.02386352,  0.02503207,
        -0.03597945, -0.0194989 ,  0.02387352,  0.00207195, -0.02740302],
       [-0.01656395, -0.02776014, -0.00654156, -0.01475537, -0.02967867,
         0.04146253,  0.01982585, -0.02761208